### ISSUE TITLE
add * functionality to CoNLLRDFUpdater

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#1]
add * functionality to CoNLL2RDF and CoNLLRDFUpdater

**Comment by cfaeth** [comment]
* functionality has been added to CoNLLRDFUpdater.
Merging into CoNLL2RDF still pending.

**Comment by chiarcos** [comment]
see issue 2: reimplement iterators to run no more than applicable (~ *), but eliminate * as a symbol.
