### ISSUE TITLE
Parallelization of CoNLLRDFUpdater

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#12]
feature request: process sentence-level models in parallel threads.
reason: sentence-level models are small, but complex SPARQL Updates require some search effort => sequential approach blocks processing next sentence

requires:
- static variables for CoNLLRDFUpdater modules (= external resources)
- make sentence-level models non-static
- multithreading for SPARQL Update operations (on sentence-level models)
- serialization and job synchronization for sentences (spell out in same order)
- parameter for the number of parallel threads

**Comment by cfaeth** [comment]
Has been implemented in latest commit. See commit message for details.
0f525dedc9aadbf7db0168f38e01daa011d40a5c
