### ISSUE TITLE
Running the tutorial in Ubuntu with OpenJDK

### ISSUE THREAD

**Issue by francescomambrini** [acoli-repo/conll-rdf#15]
You might want to add to the documentation and/or the hands-on tutorial that, if running the code with OpenJDK, one needs to install `openjfx`, or it will fail to load `javafx`:

```
sudo apt-get install openjfx
```

It might save somebody some headaches... ;-)

See [this answer here](https://stackoverflow.com/questions/32630354/the-import-javafx-cannot-be-resolved/34244725).

**Comment by cfaeth** [comment]
Just updated the readme. Thanks a lot for pointing this out!
