### ISSUE TITLE
Asterisk symbol as parameter

### ISSUE THREAD

**Issue by deshoe20** [acoli-repo/conll-rdf#2]
The asterisk * seems not to be working properly (out of the box) as a parameter as it functions as a special symbol in various shells. The current implementation leads to a default 1 for cygwin and error msgs when called from windows console. My suggestion would be to change the symbol for unlimited repetition of an update to the character u/U as already implemented for the CoNLL2RDFUpdater.

**Comment by chiarcos** [comment]
Remove the * operator, but perform numbered iterations only as long as they apply. Otherwise, we cannot guarantee that a pipeline terminates.
