### ISSUE TITLE
-silent flag

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#39]
Option to suppress general usage information on the command line (suppressing just synopsis and general logging info, not error messages), for all classes that have a main() method.

**Comment by leogott** [comment]
I can add that with the command-line-parsing rework.

I'll add a `-silent` flag to every pipeline component, to configure the logger to filter out "info" messages.

There is the option of changing the default behavior to not display the usage help, and instead add a `-help` flag, with which it only prints the help, and exits.
