### ISSUE TITLE
Support gzipped custom models in CoNLLRDFUpdater

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#4]
Please enable the following:

CoNLLRDFUpdater -custom -model http://wordnet-rdf.princeton.edu/static/wordnet.nt.gz http://wordnet-rdf.princeton.edu/

detect from *gz extension and pipe model through java.util.zip.GZIPInputStream before parsing

**Comment by cfaeth** [comment]
implemented by deshoe, tested
