### ISSUE TITLE
Minor -graphsout requests

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#7]
- report changes only: Except for the initial graph, spell out dot only if an operation changes the graph
- include SPARQL: add a text field below the dependency view and the (hidden nodes) in graph view that contains the update (in SPARQL)

**Comment by cfaeth** [comment]
report changes only: works

include SPARQL: does not work yet, although it seems to be implemented. DOT files does not contain any trace of updates. Debugging needed. Tested with examples/parse-du+graphviz.sh

**Comment by cfaeth** [comment]
SPARQL Update is displayed now. 

Problem 1: For large .sparql files with multiple updates, it is not visible which step has been performed. Solution: do not display full content of update file, but only the currently performed step. 

Problem 2: Still some smaller issues when converting to PNG. This happens in parse-du+graphviz.sh:
Error: in routesplines, illegal values of prev 1 and next 1, line 480
[1]+  Segmentation fault      (core dumped) dot -Tpng $file -o $file.png
Warning: Unable to reclaim box space in spline routing for edge "Bhttps://github.com/UniversalDependencies/UD_English#s2_18" -> "Bhttps://github.com/UniversalDependencies/UD_English#s2_15". Something is probably seriously wrong.

**Comment by deshoe20** [comment]
Problem 1 is solved with operation.toString().

But Problem 2 is two separate issues not yet solvable - further investigation required.
In regard to the "Warning: Unable to reclaim box space in spline routing for edge" - seems like a bug in the dot-engine (atleast google results suggest it), if I replace label with xlabel I get no more warning but layout is broken ofc.
I have not yet looked into the error into seg fault issue.

**Comment by leogott** [comment]
The og issue, and the problems @cfaeth outlined were solved, as far as I can tell.
If someone can still reproduce the issue, please attach a sentence+rdf that causes them. :slightly_smiling_face:

Until then we can consider this issue fixed!
