### ISSUE TITLE
revise `compile.sh`

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#73]
We support compilation with maven (default) and direct compilation (`compile.sh`, for compilation in built scripts). The latter got out of sync and was broken. It now resorts to maven. However, this is a preliminary hack, as it does re-build everything at every call, logging is verbose and it doesn't seem to find the test directory.

TODO: Fix maven call ;)

For a sample call, run 

    $> git clone https://github.com/acoli-repo/conll-transform.git
    $> cd conll-transform
    $> ./transform.sh CoNLL-U CoNLL-12

If it doesn't find a `conll-rdf` directory, it clones and re-builds it from scratch. Try that to get the logging.

(See [CoNLL-Transform Issue #5](https://github.com/acoli-repo/conll-transform/issues/5))

**Comment by cfaeth** [comment]
We should consider to remove support for legacy (non-maven) compilation, specifically to also merge the fintan-support branch into master:

* we can remove the lib folder (and do not need to provide a precompiled Fintan core lib there, which would need manual updates)
* we can fully rely on Maven modules for a unified build script.
* This would greatly simplify and stabilize the project.

Question: do we still need support for legacy, non-maven javac compilation, support for heterogeneous Cygwin environments etc?

**Comment by chiarcos** [comment]
removing `lib/`: +1
relying on maven: +1
removing compile.sh: -1 / instead: can we just make it call maven?

we need `compile.sh` for old workflows with `run.sh` (and its derivatives)
as some of these include calls to `compile.sh`. These are mostly in-house
pipelines, but many of them.

Am Fr., 3. Dez. 2021 um 16:07 Uhr schrieb cfaeth ***@***.***>:

**Comment by leogott** [comment]
Just for clarification:
I will rewrite compile.sh to call maven (with certain flags like --batch-mode and --quiet, intended to make operation from inside a script reliable).
Intended behavior is

- run.sh
  - **calls compile.sh,** then
  - calls conll-rdf classes via maven (exec) with provided arguments

- compile.sh
  - checks if a recompile is necessary, then
    - calls maven to recompile the project
  - or if invoked with -f / manually
    - calls maven with clean-goal first, then recompiles

**Comment by leogott** [comment]
I tried to check out conll-transform and ran into a few problems.
I tested it by re-adding the lib folder manually (by checking out commit 1ba1a17 of #76) and then running `java -Dfile.encoding=UTF8 -cp bin/:conll-rdf/lib/* org/acoli/conll/transform/Transformer -version 1 CoNLL-U CoNLL-12 conll-rdf/owl/conll.ttl`.
It seems to work?
