### ISSUE TITLE
question regarding parsing NER from MISC field to CoNLL RDF

### ISSUE THREAD

**Issue by obkhan** [acoli-repo/conll-rdf#84]
I have been using stanza to generate NER types that then I convert to CoNLL using a modified version of their export function.  Now they have added the NER field in the MISC tag as below:

https://github.com/stanfordnlp/stanza/pull/996/commits/e3fbf8c76925a7acb5dd619d550213dee0d5bcc7

Any suggestions/thoughts about using conll-rdf to process the pipe delimited MISC in a meaningful way for conll-rdf NER  transformation?

**Comment by chiarcos** [comment]
Can you provide a data snippet? If the question is how to parse multiple
`|`-separated values from a single CoNLL cell/string, you can use the
Apache Jena SPARQL extensions, as CoNLL-RDF and Fintan are based on Apache
Jena.

PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>

INSERT {

 ?w conll:SPLIT_MISC ?split

} WHERE {

 ?w conll:MISC ?misc.
 ?split apf:strSplit(?misc "|").
}

Note that this is not part of the SPARQL 1.1 spec, but specific to Jena,
that other SPARQL engines use different vocabulary for this purpose and
that we do not guarantee that future versions of CoNLL-RDF will also be
built on Apache Jena. (Although it looks like that for the moment.)
A more portable (but much slower) alternative is to loop over a SPARQL
update that strips off the first string before `|` using
`BIND(strbefore(?misc,"|") as ?split)` and `BIND(strafter(?misc,"|") as
?misc)` (and updating `?misc` in every iteration).


Am Do., 14. Apr. 2022 um 00:30 Uhr schrieb obkhan ***@***.***

**Comment by chiarcos** [comment]
Also note that if you do this kind of splitting operation and then want to serialize it into CoNLL afterwards, again, you should re-merge the annotations to make sure you have a single value for, say, `conll:MISC`:

	DELETE {
		?w conll:MISC ?misc.
		?w conll:SPLIT_MISC ?split.
	} INSERT {
		?w conll:MISC ?merged.
	} WHERE {
		?w conll:SPLIT_MISC ?split.
		{ SELECT ?w (GROUP_CONCAT(distinct ?s; separator="|") as ?merged)
		  WHERE { 
			  ?w conll:SPLIT_MISC ?s 
		  } GROUP BY ?w
		}
		OPTIONAL { ?w conll:MISC ?misc }
	};

If you don't do that, the default behaviour of CoNLL-RDF is to provide `|`-concatenated values *for every possible variable binding*, even if the values are the same.

**Comment by obkhan** [comment]
@chiarcos  thanks so much for the well thought out response , it helps!

The source for the CoNLL was parsed with beautiful soup/bs4 from : 

https://www.richmondfed.org/publications/research/coronavirus/economic_impact_covid-19_11-10-21
How Charlotte’s Banks Responded to COVID-19
By Elizabeth Medlin - The Federal Reserve Bank of Richmond (
Views expressed in this article are those of the authors and not necessarily those of their respective Reserve Banks or the Federal Reserve System.)

Then Stanford's stanza library version 1.3.1 (dev) used to create NER tags, then saved to the attached conllu file
[economic_impact_covid.conllu.zip](https://github.com/acoli-repo/conll-rdf/files/8503235/economic_impact_covid.conllu.zip)

**Comment by chiarcos** [comment]
Does the following work?

    PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>
    INSERT {
     ?w conll:NER ?ner
    } WHERE {
     ?w conll:MISC ?misc.
     ?split apf:strSplit(?misc "|").
     FILTER(strstarts(?split,"ner="))
     BIND(strafter(?split,"=") as ?ner)
    }

If so, please close the issue.

**Comment by obkhan** [comment]
It is very close to what I was trying to do I had to add \\| to escape the pipe and prefix as follows for economic_impact_ner.sparql:

`PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>
INSERT {
 ?w conll:NER ?ner
} WHERE {
 ?w conll:MISC ?misc.
 ?split apf:strSplit(?misc "\\|").
 FILTER(strstarts(?split,"ner="))
 BIND(strafter(?split,"=") as ?ner)
}`

I also had a minor challenge with the pipeline when putting piped output together, sometimes the below would hang? 
`cat ./economic_impact_covid.conllu | ../run.sh CoNLLStreamExtractor my-baseuri.org/example.conll# ID TEXT LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC | ../run.sh CoNLLRDFUpdater -custom -updates ./economic_impact_ner.sparql > economic_impact_covid_ner.ttl`

I found if I split the commands into two steps, as follows it worked fine:
`cat ./economic_impact_covid.conllu | ../run.sh CoNLLStreamExtractor my-baseuri.org/example.conll# ID TEXT LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC > economic_impact_misc_no_ner.ttl`
`cat ./economic_impact_misc_no_ner.ttl | ../run.sh CoNLLRDFUpdater -custom -updates ./economic_impact_ner.sparql > economic_impact_covid_ner.ttl`

First I tried the above on Windows, but then later had the same behavior on a MacOS. 

I'll close, but wanted to add those comments in case someone runs into the above.
